examples/simulated/regression.py
ngboost/distns/normal.py
ngboost/scores.py

@avati would appreciate a second look.
Adding `D_crps` for the Normal distribution to allow use of CRPS, see the derivation below.

Add CRPS gradient for Normal distn.

---

ngboost/learners.py

- delete "import LinearRegression" code in ngboost.learners.

delete unused import LinearRegression

---

README.md
examples/empirical/clf_sklearn.py
examples/empirical/reg_sklearn.py
ngboost/__init__.py
ngboost/ngboost.py
ngboost/sklearn_api.py

- add scikit-learn API models; Regressor and (Binary)Classifier
- also add their examples to use GridSearchCV reported in [this isssue](https://github.com/stanfordmlgroup/ngboost/issues/7).

Add scikit-learn API

---

ngboost/evaluation.py
ngboost/learners.py
ngboost/scores.py
ngboost/sklearn_api.py

- clean code
- fix argument in default_linear_learner

fix argument alpha in default_linear_learner

---

ngboost/distns/lognormal.py
ngboost/distns/normal.py
ngboost/ngboost.py

@avati would appreciate a second look.
Adding the CRPS and D_CRPS for right-censored LogNormal distribution. 
Also some general cleanup for that file.
See the derivation below. The Owen reference is specifically top of page 400 in [1], or also in [2].
[1] https://www.tandfonline.com/doi/abs/10.1080/03610918008812164
[2] https://en.wikipedia.org/wiki/List_of_integrals_of_Gaussian_functions

Add CRPS and D_CRPS for LogNormal.

---

ngboost/scores.py

- remove unused arguments in scores.py

remove unused arguments

---

ngboost/distns/__init__.py
ngboost/distns/multivariate_normal.py

add multivariate distribution parametrized with mean vector and cholesky factor. Gradient of NLL was numerically checked. Fisher information follows [1] under Matrix form -> Multivariate Normal distribution. The Jacobian of Sigma, Cholesky factor was from [2], verified solution.
https://en.wikipedia.org/wiki/Fisher_information
https://mathoverflow.net/questions/150427/the-derivative-of-the-cholesky-factor

Multivariate

---

ngboost/api.py

- Add predict_proba method to NGBClassifier to fix https://github.com/stanfordmlgroup/ngboost/issues/38.

Add predict_proba method to NGBClassifier

---

ngboost/ngboost.py

Check whether the base model is of class DecisionTreeRegressor

Add quick fix for feature importance regressor class check

---

ngboost/api.py

fix indentation problem on api

 fix indentation and random_state

---

.github/workflows/pythonpackage.yml

https://github.com/stanfordmlgroup/ngboost/pull/91#issuecomment-588614656

remove pre-commit run

---

.github/workflows/pythonpackage.yml
Pipfile
Pipfile.lock

Proposal of package management by pipenv #97

Use Pipenv

---

README.md

[markdownlint](https://github.com/DavidAnson/markdownlint)

Fix description according to markdownlint

---

examples/classification.py

`preads` do not have `prob` but have `probs`

fix classification sample code

---

examples/simulations/regression_sim.py
ngboost/distns/distn.py
ngboost/distns/normal.py
ngboost/manifold.py
setup.py

Fixed the format of some codes.

Minor fixes

---

examples/tuning/hyperopt.ipynb

I've created this simple example on how to run hypteropt with ngboost to tune hyper-parameters on a smaller space and thought it would be useful to include as an example to the library. Thanks for your time reviewing!
Ryan

Hyperopt example

---

ngboost/distns/normal.py
ngboost/ngboost.py
ngboost/version.py

Also minor edits in line search

remove arbitrary stability constant in fisher information

---

ngboost/version.py

Hey guys, 
Just decided to make this pr to make the update to pypi with the addition of the new distribution. I think docs updates need to be made but we can do that in 0.3.1 after @alejandroschuler figures out the issues with jupyterbook.
Thanks!

update version with new dist

---

examples/classification.py
examples/experiments/regression_exp.py
examples/experiments/survival_exp.py
examples/multiclass_classification.py
examples/poisson.py
examples/simulations/regression_sim.py
examples/simulations/survival_sim.py
figures/toy.py
figures/toy_single.py
figures/vis_mle.py
ngboost/version.py

Made some more linting updates to /examples and /figures

More linting

---

MANIFEST.in

It would be helpful to include the license file in the source distribution.

Create MANIFEST.in and package license file

---

ngboost/ngboost.py

This PR attempts to fix the issue mentioned in #181 , where when `col_sample` was used (i.e. < 1) the feature importance was only grabbing for the columns that were selected in building each trees. All columns feature importance should be retrieved.
Approach:
`self.col_idxs` contains the column indices that were sampled when building each trees, so we can get the feature importance of these sampled columns and then map back to the total features.
Test:
Did not perform unittest etc., if it's highly preferred please let me know and kindly provide some guidelines.
So for basic testing, I have run experiments with `col_sample` range from really low values e.g. 0.1 to 0.9 and 1., in combination with different number of `n_estimators` range from 10 ~ 1000, and the code finished without error …

Issue #181 - fix feature importance when col_sample < 1

---

ngboost/distns/poisson.py

closes #191 
Derivation by hand:

Add Poisson exact fisher

---

ngboost/distns/laplace.py

Just a minor formatting update that was missed in a previous commit

clean up formatting on lines of laplace dist

---

pyproject.toml

update dependency for tqdm

---

README.md

update readme with conda forge instructions

---

tox.ini

for testing against multiple python versions locally
more info about tox is available at https://tox.readthedocs.io/en/latest/

Setup tox to enable testing with multiple python versions locally

---

pyproject.toml

bumping the version for the addition of the new dist and tests

bump version to 0.3.10

---

ngboost/api.py

Small typos in the comment section of NGBClassifier and NGBSurvival classes.

There were some typos.

---

ngboost/api.py
ngboost/distns/utils.py
ngboost/ngboost.py
pyproject.toml
tests/test_distns.py
tests/test_pickling.py

- Made NGBSurvival pickleable. This will not work if the base Dist is not pickleable itself. I assume this would be quite rare though?
- Added pickle tests from the test-pickle branch. I hope it gives credit to Ryan as it is all their code! I think I used checkout to copy it directly from the branch.
- Testing was taking quite a while so I turned down the number of iterations in the MVN test and the pickle tests
- Fixed a small typo in the __getstate__ comments.
Should close 
https://github.com/stanfordmlgroup/ngboost/issues/238
https://github.com/stanfordmlgroup/ngboost/issues/228
Can change any of it/try to improve it if anyone has any ideas!

Survival pickle

---

.github/workflows/pythonpackage.yml
.pre-commit-config.yaml
Makefile
examples/simulations/regression_sim.py
figures/toy.py
figures/toy_single.py
ngboost/distns/laplace.py
ngboost/distns/lognormal.py
ngboost/distns/normal.py
ngboost/distns/t.py
ngboost/distns/utils.py
pyproject.toml
tests/conftest.py
tests/test_basic.py
tests/test_distns.py
tests/test_pickling.py

Upgrade black formatter to newest version.

Fixing black formatter

---

README.md

Centre readme buttons and more buttons - repo size, version number on pypi, pypi downloads. 
PR mainly because I wanted to get the reposize at a glance.

Improve Buttons in README

---

RELEASE_NOTES.md
pyproject.toml

Bumping the version for a release of partial fit and adding release notes

release partial fit 0.4.1

---

RELEASE_NOTES.md
pyproject.toml

* Allow NAN as input
* Poetry update

update for 0.5.3 release

---

RELEASE_NOTES.md
pyproject.toml

* Update to partial fit to respect validation data

0.5.4 release

---

README.md

fix broken package image

---

ngboost/ngboost.py
pyproject.toml

bump sklearn to 1.6 and rename deprecated parameters

---

RELEASE_NOTES.md
pyproject.toml

 v0.5.5 release

---

RELEASE_NOTES.md
pyproject.toml

* Add support for Weibull and HalfNormal Distributions

release 0.5.6
