stanfordmlgroup/ngboost

ngboost/ngboost.py

Add verbose_eval option to NGBoost to reduce loss history on a log like LightGBM etc.
Usage:
If ` verbose_eval=10` then loss history is shown at every 10 iteration.
```
ngb = NGBoost(Base=default_tree_learner, Dist=Normal,
Score=MLE(), natural_gradient=True, verbose=True, 
verbose_eval=10)
```

Add verbose_eval option.

---

ngboost/__init__.py

Proposing that we have NGBoost importable from top-level module.
Doing so will improve the import API, such that it now reads as follows:
```python
from ngboost import NGBoost
```
rather than
```python
from ngboost.ngboost import NGBoost
```
(The latter can sometimes be confusing for not-so-seasoned Python programmers.

Import NGBoost class  into __init__

---

examples/inspections/Feature importance.ipynb
ngboost/ngboost.py
requirements.txt

Follow-up on #27. 
For default_tree_learners, added sklearn-like feature importance.
The resulting feature importance is a numpy array with number of parameters in the distribution as number of rows and number of features in the training data as number of columns.
Please check out the [notebook](https://github.com/zhiruiwang/ngboost/blob/feature_importance/examples/inspections/Feature%20importance.ipynb) for testing examples.

Add feature importance functionality for tree learners

---

ngboost/__init__.py
ngboost/api.py
ngboost/distns/__init__.py
ngboost/distns/categorical.py
ngboost/distns/distn.py
ngboost/distns/normal.py
ngboost/manifold.py
ngboost/ngboost.py
ngboost/scores.py

Here’s a summary of the refactor:
For distributions, the top level class is `Distn`, which implements default methods for slicing and indexing. This class has two subclasses: `RegressionDistn` and `ClassificationDistn`, which implement the appropriate methods for prediction (mean for regression, mode for classification). Each distribution (e.g. `Normal`) is a subclass of one of these two classes. Each distribution implements the parameters of that distribution as well as methods for fitting the marginal and sampling. All `RegressionDistn`s must additionally implement `mean()` and `ClassificationDistn`s must implement `class_probs()`.
The most specific scoring rule is a “distribution score” (e.g. `NormalLogScore`), which typically implements `score()`, `d_score()`, and `metric()` methods …

Manifold refactor

---

setup.py

The current `long_description` in `setup.py` makes it difficult for users to get information when viewing [pypi page](https://pypi.org/project/ngboost/). Therefore, I modified setup.py so that the contents of README.md are reflected on the pypi. Other projects such as `lightgbm`, `xgboost` adopt this approach.

Get long description from README.md

---

ngboost/api.py
ngboost/helpers.py
ngboost/ngboost.py

This is for changes discussed in https://github.com/stanfordmlgroup/ngboost/pull/128
Changes Implemented:
used sklearn functions to validate user inputs for support of pandas dataframe , list, or arrays.
There are also validations for strings or null values which are prohibited

Dataframe compatibility for inputs for fit and predict functions

---

ngboost/version.py
setup.py

Closes https://github.com/stanfordmlgroup/ngboost/issues/164
This update will create an obvious failure when installing on unsupported versions.

Update setup py 3

---

docs/5-dev.html
examples/user-guide/content/5-dev.ipynb
ngboost/distns/__init__.py
ngboost/distns/laplace.py

This should fix #177 by addressing the documentation typo in log-likelihood gradient.
Moreover I realized we might as well add the complete Laplace distribution to the package. The implementation here supports both LogScore and CRPScore. 
For future reference I calculated the Fisher Information here as variance of the score, using the following Mathematica code.
```
Expectation[ (Abs[y-m]/b-1)^2,y \[Distributed] LaplaceDistribution[m,b]]
Expectation[-1/b Sign[m-y] (Abs[m-y]/b-1),y \[Distributed] LaplaceDistribution[m,b]] 
```
The CRPS for the Laplace is given in [[Jordan et al. 2019]](https://www.jstatsoft.org/index.php/jss/article/view/v090i12). 
The information metric involved integrals calculated with the following Mathematica code:
```
Integrate[0.25 / …
```

Fix Laplace docs and add Laplace distribution.

---

.github/workflows/pythonpackage.yml
.gitignore
conftest.py
ngboost/distns/__init__.py
ngboost/tests/test_basic.py
ngboost/tests/test_distns.py
ngboost/version.py
pytest.ini

In reference to https://github.com/stanfordmlgroup/ngboost/issues/41
Hey all! Am trying to get familiar with this library, so started by messing about with the unit testing that's
currently in place. I saw the opportunity for a couple of changes that I recommend, so here is a PR with the changes implemented. 
For the most part, the actual testing has remained unchanged but the layout has been altered to fit with `pytest.mark.parametrize` for the parameterized tests in `distns`. 
Additionally, some of these tests take quite some time, so I've added in a `--slow` toggle to be able to only run fast tests during a development loop. Hopefully, this will make more testing a lot less painful!
Here is what the parametrized tests look like 
There are still a very large number of warnings that …

Parametrization in Pytest and --slow mark 

---

Makefile

Sorry peeps! All good now:
```bash
~/code/misc/ngboost fix/makefile
ngboost ❯ make package
poetry build
Building ngboost (0.3.8dev)
- Building sdist
- Built ngboost-0.3.8.dev0.tar.gz
- Building wheel
- Built ngboost-0.3.8.dev0-py3-none-any.whl
~/code/misc/ngboost fix/makefile*
ngboost ❯ make publish
poetry build
Building ngboost (0.3.8dev)
- Building sdist
- Built ngboost-0.3.8.dev0.tar.gz
- Building wheel
- Built ngboost-0.3.8.dev0-py3-none-any.whl
poetry publish
Username: *****
Password: ******
```

Fix `make package` typo in Makefile

---

ngboost/__init__.py
pyproject.toml
tests/test_version.py

This PR enables
```
python -c 'import ngboost; print(ngboost.__version__)'
0.3.8.dev0
```

supported version checking via ngboost.__version__

---

.github/CODEOWNERS
pyproject.toml

This PR will close #233 
This will automatically add the people in the codeowners file to the reviewers list on PRs. I'm also updating the version before I publish a new version of the package to make recent changes live on pypi
Thanks,
Ryan

add codeowners file and bump version for latest merges

---

examples/multivariate_normal.py
ngboost/distns/multivariate_normal.py
ngboost/ngboost.py
tests/test_distns.py
tests/test_score.py

**Implementation of multivariate  normal distribution just for regression with LogScore.**
It does not use the scipy implementation primarily as I found scipy was much slower.
Got the idea from a paper I mentioned in the doc string of `distns.multivariate_normal`. I recreated one of the experiments from the paper in `experiments/multivariate_normal.py` and results seem very similar.
Here's a sanity check I did against a tensorflow implementation for a 3 dimensional multivariate normal, I can share my calculations for the Fisher Information soon if needed, they are currently very messy.
[mvn_comparison.pdf](https://github.com/stanfordmlgroup/ngboost/files/6015943/mvn_comparison.pdf)
*Deleted the old implementation*
I did override the old MultivariateNormal class. I salvaged a few bits (the …

Multivariate normal implementation

---

ngboost/api.py
ngboost/ngboost.py

Allow sparse `X` when fitting and predicting - fixes #271.
An example using the new version:
```python
from ngboost import NGBSurvival
import numpy as np
import scipy.sparse as sp
from time import perf_counter
def generate_X_T_E(n, d):
X = np.random.choice(2, p=[0.9, 0.1], size=(n, d))
T = np.random.rand(n)
E = np.random.randint(2, size=n)
return X, T, E
n_train = 10000
n_val = 1000
d = 3000
X, T, E = generate_X_T_E(n_train, d)
X_val, T_val, E_val = generate_X_T_E(n_val, d)
ngb = NGBSurvival(n_estimators=101, learning_rate=0.1, verbose_eval=10, random_state=0)
t0 = perf_counter()
ngb.fit(X, T, E, X_val=X_val, T_val=T_val, E_val=E_val, early_stopping_rounds=50)
print(perf_counter() - t0, "s")
t0 = perf_counter()
y_dists = ngb.pred_dist(X_val)
print(perf_counter() - t0, "s") …
```

Allow sparse X, fixes #271

---

ngboost/ngboost.py

Fix off-by-one error (issue #302) when specifying maximum number of trees to use

---

pyproject.toml

flake8 does not need to be installed with the shipped package. This will reduce the number of installed packages from `pip install ngboost`

Shift flake8 to dev dependencies

---

pyproject.toml

Pandas is not required at run-time nor during development. It is required to run the example notebooks, but these seem to have separately tracked requirements [here](https://github.com/stanfordmlgroup/ngboost/blob/master/examples/user-guide/requirements.txt) and [here](https://github.com/stanfordmlgroup/ngboost/blob/master/docs/requirements.txt).
Note that lifelines (used in `ngboost.evaluation`) does require pandas, so ngboost still requires it transitively. Lifelines has a less stringent pandas requirement than what's currently provided.

Remove declared pandas dependency

---

README.md
examples/regression.py
examples/survival.py
pyproject.toml

Update load_boston in README.md

---

tests/test_distns.py

This pull request introduces improvements to our test suite, resulting in a substantial reduction in build and test run times. Previously, our tests took approximately 45 minutes to complete. With the changes implemented in this PR, the test suite now completes in about 15 minutes. This represents a time savings of approximately 67%, a substantial improvement that enhances the efficiency of our development process. The reduced test run time will make it easier and more convenient for developers to run tests before committing code to the repository. 
The optimization was achieved by modifying the test setup to sample 1000 records once and pass them to each test. This approach is more efficient and still allows us to thoroughly test our functions.

speed up tests by loading sample once

---

ngboost/ngboost.py

Hi,
I was recently working on a project and when inspecting resource usage realized memory consumption was way too high for `.pred_dist()` when passing a `max_iter` value other than `None`.
When inspecting the code, I realized that the issue stemmed from using `.staged_pred_dist()` but only returning the last value. This resulted in unnecessary memory allocation (in my case hundreds of GBs).
```
if (
max_iter is not None
):  # get prediction at a particular iteration if asked for
dist = self.staged_pred_dist(X, max_iter=max_iter)[-1]   <-- Only using last Dist obj, but allocates memory for max_iter * Dist objects
```
Also, the conditional statement wasn't really needed. All it was checking for is if `max_iter` is `None` or not, but `pred_param()` can already handle that case.
This PR …

Fix issue causing large memory consumption in pred_dist()

---

.github/workflows/pythonpackage.yml
pyproject.toml

Closes #345 
- Adds support for python 3.12, and adds to the CI matrix
- Removes support for python 3.8, removes from the CI matrix
- Updates the pinned versions of flake8 and pylint
It was seemingly necessary to drop support for python 3.8 to enable poetry to allow numpy `1.26`. If 3.8 support is retained, poetry only allows numpy up to `1.24` which has a bug on python 3.12: https://github.com/numpy/numpy/issues/23808
According to [SPEC 0](https://scientific-python.org/specs/spec-0000/) (which superseded [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html)), python 3.8 is overdue to be dropped:
> On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)

Add support for python 3.12, drop python 3.8

---

RELEASE_NOTES.md
pyproject.toml

Given significant changes to Python support this release bumps the minor version up.
* Drops support for python 3.7 and 3.8
* Now supports Python 3.11 and 3.12
* Fixed issue with np.bool
* Optimized memory usage in pred-dist
* Removed declared pandas dependency
* Significant improvements to run times on tests during development
* Minor enhancements to github actions

Release 0.5.0

---

Makefile
RELEASE_NOTES.md
pyproject.toml

This PR is intended to make the PYPI publishing easier by setting the api token in a .env file. Also updates clean to just remove old dist files after publishing a release so later versions are not re-uploaded.
example .env
`PYPI_TOKEN=your_token`

Makefile updates

---

ngboost/api.py
ngboost/ngboost.py
ngboost/scores.py
pyproject.toml

Currently, ngboost doesn't support Numpy 2.* due to a breaking change that was made for `numpy.linalg.solve`: see [#25914](https://github.com/numpy/numpy/pull/25914).
To give a brief explanation, `numpy.linalg.solve(a,b)` accepts two forms of input, either `a` as an `...xMxM` and `b` as an `...xMxK` matrix, where `numpy.linalg.solve` will treat `ax = b`, with `x` the `...MxK` matrix that solves this equation. The other form accepts `a` as an `...xMxM` and `b` as an `...xM` matrix, with `x` the `...xM`matrix that solves this equation. The `...` represent dimensions that view the problem as a set of solutions for stacked matrices/vectors, termed [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html). Previous versions of numpy inferred that the calculation should be of …

Add support for Numpy 2.*, fix linting issues

---

Makefile

Updating `poetry` to version 2.0.1 as the current pinned version in `Makefile` is 1.2.1 and quite old at this point. Version 2.0.1 is compatible with Python 3.9 which is the minimum required for `ngboost` at the moment. A lot of improvements to `poetry` have been made from 1.2.1 to 2.0.1 and can be found [here](https://github.com/python-poetry/poetry/releases).

Updating poetry

---

ngboost/ngboost.py

This change allows NaNs in X (in train, validation, and test) matching what is permitted by XGBoost.

Allow NaNs in input X

---

ngboost/ngboost.py
pyproject.toml

Existing logic ignores passed validation data, the if erarly_stopping_rounds control sequence is updated to respect the passed validation data.

Update partial_fit to respect validation data

---

README.md
examples/regression.py
examples/survival.py

This fixes the `SyntaxWarning: invalid escape sequence '\s'` warning in the examples.

fix: syntax warning in examples

---

ngboost/ngboost.py

The two parameters `validation_fraction` and `early_stopping_rounds` have been added to the `params` dictionary.
See issue on cloning the model: #382

Update parameters in `get_params`

---

ngboost/ngboost.py

**Improved Column Sampling for Small Datasets**
In our current implementation, `col_sample` is treated as a percentage. When the number of columns is small and `col_sample` is also small, calculating the sampled columns with:
```
col_size = int(self.col_sample * X.shape[1])
```
can result in `col_size` being 0.
For example:
if there are 4 columns and `col_sample = 0.1`, then `int(0.1 * 4)` yields 0, which subsequently causes an error during model generation due to having 0 input features.
This pull request updates the logic to ensure that at least one column is always selected when `col_sample` is positive by using:
```
col_size = max(1, int(self.col_sample * X.shape[1])) if self.col_sample > 0 else 0
```
This change prevents errors in cases with a small number of features, improving the …

fix: make col_sample min equals to 1

---

ngboost/distns/__init__.py
ngboost/distns/weibull.py
tests/test_distns.py
tests/test_score.py

Added the Weibull distribution (`scipy.stats.weibull_min`) with shape and scale parameters.
- The Weibull distribution has support for LogScore
- Added Weibull LogScore to the `test_dists_metric` test
- Added Weibull distribution to the `test_dists_runs_on_examples_logscore` test

Added Weibull Distribution

---

.pre-commit-config.yaml
RELEASE_NOTES.md
examples/simulations/regression_sim.py
examples/user-guide/scripts/clean.py
figures/vis_crps.py
figures/vis_mle.py
ngboost/distns/__init__.py
ngboost/distns/categorical.py
ngboost/distns/cauchy.py
ngboost/distns/distn.py
ngboost/distns/exponential.py
ngboost/distns/gamma.py
ngboost/distns/halfnormal.py
ngboost/distns/laplace.py
ngboost/distns/lognormal.py
ngboost/distns/multivariate_normal.py
ngboost/distns/normal.py
ngboost/distns/poisson.py
ngboost/distns/t.py
ngboost/distns/utils.py
ngboost/distns/weibull.py
pyproject.toml
tests/test_distns.py

This PR updates all development dependencies to their latest versions and modernizes the project configuration to follow current best practices.
- **pytest**: `^6.1.2` → `^8.0.0`
- **black**: `^22.8.0` → `^24.0.0`
- **pre-commit**: `^2.0` → `^4.0.0`
- **isort**: `^5.6.4` → `^5.13.0`
- **pylint**: `^3.0.3` → `^3.2.0`
- **flake8**: `^7.0.0` → `^7.1.0`
- **Modern Poetry format**: Migrated from deprecated `[tool.poetry.dev-dependencies]` to `[tool.poetry.group.dev.dependencies]`
- **Black configuration**: Added explicit `[tool.black]` section with line length and target versions
- **Python version markers**: Improved numpy/scipy version constraints using PEP 508 markers for better clarity
- **Pre-commit updates**: 
- Updated Black version in `.pre-commit-config.yaml` to match pyproject.toml
- …

Update dev dependencies
